### ISSUE TITLE
Doesn't connect if bluetooth is off

### ISSUE THREAD

**Issue by rmodi6** [lapfelix/BluetoothConnector#10]
Not sure if this was intended, but the `BluetoothConnector` _doesn't work/exits without error_ if the bluetooth is turned off. `Readme.md` also fails to mention this requirement.
Ideally it should automatically turn on bluetooth if it is off and then attempt to connect to a bluetooth device.

**Comment by lapfelix** [comment]
Ah, I never turn off my Bluetooth so I never thought of this use case! That should be pretty easy to do 👍

**Comment by lapfelix** [comment]
Done in https://github.com/lapfelix/BluetoothConnector/commit/1178a62878ea2216ece55b9baf4deda419edf44d
