### ISSUE TITLE
Feature Request: --toggle command

### ISSUE THREAD

**Issue by dsanson** [lapfelix/BluetoothConnector#13]
I think the title says it all: it would be nice to have a `--toggle` option, so that a single alias or shortcut can be used to connect an unconnected device or disconnect a connected device.

**Comment by torifat** [comment]
It already supports toggle. Just do:
```
BluetoothConnector 00-00-00-00-00-00
```

**Comment by dsanson** [comment]
Sorry! I don't know how I missed that. Thanks.
