### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by luckman212** [lapfelix/BluetoothConnector#15]
Thank you ❤️ for this new 2.0 version! I'm using this very successfully in an Alfred4 workflow to quickly switch audio outputs.

Does the [brew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bluetoothconnector.rb) automatically get updated or does something need to be pushed? It's still providing the 1.3.0 version.

**Comment by lapfelix** [comment]
Thanks, glad you find it useful!

It's pretty easy to submit updates to homebrew. I actually did the 2.0 release just to send it to homebrew (the actual changes have been in the repo for a while): https://github.com/Homebrew/homebrew-core/pull/54183

So it should get merged/updated pretty soon!

**Comment by luckman212** [comment]
I see v2.0.0 is there now, thank you! 🚀
