### ISSUE TITLE
Add option/key --notify-cli-only

### ISSUE THREAD

**Issue by Dimentium** [lapfelix/BluetoothConnector#17]
Thank you for very usefull app!
Is it possible to add new optional key like `--notify-cli-only` ?
I want to use [Terminal Notifier](https://github.com/julienXX/terminal-notifier) for Notifications (because it can reuse last one and not pollute all Notification Center).
When I run it like this:
`BluetoothConnector 00-00-00-00-00-00 --notify | terminal-notifier -title AirPods -group Bluetooth -ignoreDnD`
I got two notifications same time (I don't want to disable notification for Script Editor).

Thank you!

**Comment by Dimentium** [comment]
Ohh.
Right now I use workaround like this:
BluetoothConnector 00-00-00-00-00-00 ; BluetoothConnector 00-00-00-00-00-00 --status | terminal-notifier -title AirPods -group Bluetooth -ignoreDnD
And it works fine!

I'm sorry for the inconvenience.

**Comment by lapfelix** [comment]
Sure, what happens if you simply omit the `--notify` parameter? (since you're already doing it with `terminal-notifier`?)

**Comment by lapfelix** [comment]
Ah perfect you got it!

**Comment by Dimentium** [comment]
> Sure, what happens if you simply omit the `--notify` parameter? (since you're already doing it with `terminal-notifier`?)

without --notify parameter there are no output for terminal-notifier 

Anyway thanks for great app! )
