### ISSUE TITLE
Turn off device?

### ISSUE THREAD

**Issue by DanielZanchi** [lapfelix/BluetoothConnector#19]
Is it possible to turn off a device with this?

I would like to turn off my mouse when my mac goes to sleep.
I small movement of the mouse turns the mac on and i would like to prevent this.

**Comment by brasilikum** [comment]
Hey @DanielZanchi
I am pretty sure that this is not possible. I am not aware of a generic bluetooth command that turns off an external device.

**Comment by lapfelix** [comment]
Yeah I'm not aware of to do this either. Will close because I think this is outside the scope of this small utility (but feel free to fork and add that, if you ever find out how to do it).
