### ISSUE TITLE
[Feature Request: read RSSI info] also show bluetooth device signal strength

### ISSUE THREAD

**Issue by futurist** [lapfelix/BluetoothConnector#24]
Is is possible also shown RSSI info when Connected?

I've searched this a method related to this:

https://developer.apple.com/documentation/iobluetooth/iobluetoothdevice/1431127-rssi

**Comment by lapfelix** [comment]
Done in [2.1.0](https://github.com/lapfelix/BluetoothConnector/releases/tag/2.1.0)
