### ISSUE TITLE
Does not connect or disconnect in OS X Ventura

### ISSUE THREAD

**Issue by PacoH** [lapfelix/BluetoothConnector#26]
It gets the devices that are paired or connected but cannot disconnect them.

`blueutil` works fine and is not difficult to use.

**Comment by lapfelix** [comment]
Try with [2.1.0](https://github.com/lapfelix/BluetoothConnector/releases/tag/2.1.0), it was built with Sonoma

**Comment by PacoH** [comment]
OK. That works. Thanks.
