### ISSUE TITLE
error or warnning message

### ISSUE THREAD

**Issue by scanolive** [lapfelix/BluetoothConnector#3]
macos10.13 swift4 

swift[56921:212676] Exception NSInvalidArgumentException thrown while decoding IOBluetoothSDPServiceRecord

**Comment by aj-ptw** [comment]
10.13 is causing bluetooth mayhem

**Comment by lapfelix** [comment]
This seems like a CoreBluetooth error. You should file a bug report here if it's still an issue: http://bugreport.apple.com
