### ISSUE TITLE
Connection works but disconnects after 5 seconds

### ISSUE THREAD

**Issue by rifaterdemsahin** [lapfelix/BluetoothConnector#4]
The connections works for 5 seconds then disconnects.

Added to Alfred and also tried from the console getting the same result
**
![image](https://user-images.githubusercontent.com/5270036/37110848-012d760a-2236-11e8-82ea-8bee4831ca76.png)
**

**Comment by lapfelix** [comment]
Hmmm and it stays connected if you connect through the Bluetooth menu bar ?
I have only tested this with my BeatsX headphones (and I assume it works with the AirPods too since it's the same Bluetooth chip), what bluetooth device are you using ?

**Comment by olivierlefloch** [comment]
FWIW, tried in Alfred (nearly identical setup) with Plantronics BBTPRO headset which otherwise has a hard time connecting, and it's working perfectly.

**Comment by lapfelix** [comment]
Yeah this doesn't seem related to this program. I'll close this issue.
