### ISSUE TITLE
After updating to Mac OS Mojave stopped working. 😩

### ISSUE THREAD

**Issue by yarintm** [lapfelix/BluetoothConnector#5]

**Comment by lapfelix** [comment]
Hmm it still works fine on my end 🤔
Maybe try checking if the service is correctly activated with a shortcut ? What happens if you run it directly from the terminal ?

**Comment by yarintm** [comment]
good suggestion. I got the error:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

quick google search and the fix was the command: xcode-select --install
Thank you
