### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tilmanginzel** [lapfelix/BluetoothConnector#9]
Hi @lapfelix,

thanks for this handy wrapper to quickly connect / disconnect Bluetooth devices. I would like to use the compiled binary in a custom Alfred 3 workflow, which I want to open source on GitHub (ideally under MIT).

Do you mind adding a license to this repository so that me and others can be sure that we are allowed to use your BluetoothConnector?

Cheers :)

**Comment by lapfelix** [comment]
Yeah I think this makes sense! I'll add an MIT license.

**Comment by lapfelix** [comment]
Done

**Comment by tilmanginzel** [comment]
Awesome, that was fast. Thanks a lot! :)
